/**
 * PowerPoint Document Styles
 *
 * Consistent styling for PowerPoint presentations generated by the platform.
 * Uses "Executive Clarity" theme - Navy primary, Gold accents.
 *
 * Story 18.4: PowerPoint & PDF Generation
 * Task 1.2: Create PowerPoint style constants
 * Covers: NFR28 (Board-presentation ready)
 */

/**
 * Brand colors in hex format for PowerPoint
 */
export const PPTX_COLORS = {
  navy: '0F172A',
  slate: '334155',
  gold: 'D97706',
  lightGray: 'F1F5F9',
  mediumGray: 'E2E8F0',
  white: 'FFFFFF',
  red: 'DC2626',
  green: '16A34A',
  amber: 'F59E0B',
} as const;

/**
 * Attribution text for book reference
 */
export const ATTRIBUTION_TEXT =
  'Based on The Last Paradigm methodology | thelastparadigm.com';

/**
 * Standard font families
 */
export const FONTS = {
  heading: 'Calibri',
  body: 'Calibri',
} as const;

/**
 * Font sizes in points
 */
export const FONT_SIZES = {
  title: 44,
  subtitle: 28,
  heading: 32,
  subheading: 24,
  body: 18,
  small: 14,
  caption: 12,
} as const;

/**
 * Slide dimensions (16:9 widescreen)
 */
export const SLIDE_DIMENSIONS = {
  width: 10, // inches
  height: 5.625, // inches (16:9 ratio)
} as const;

/**
 * Common margins and padding
 */
export const MARGINS = {
  slide: {
    left: 0.5,
    right: 0.5,
    top: 0.5,
    bottom: 0.5,
  },
  content: {
    left: 0.75,
    right: 0.75,
    top: 1.0,
    bottom: 0.75,
  },
} as const;

/**
 * Title slide styles
 */
export const TITLE_SLIDE_STYLE = {
  title: {
    x: 0.5,
    y: 2.0,
    w: 9.0,
    h: 1.0,
    fontSize: FONT_SIZES.title,
    fontFace: FONTS.heading,
    color: PPTX_COLORS.navy,
    bold: true,
    align: 'center' as const,
  },
  subtitle: {
    x: 0.5,
    y: 3.2,
    w: 9.0,
    h: 0.6,
    fontSize: FONT_SIZES.subtitle,
    fontFace: FONTS.body,
    color: PPTX_COLORS.slate,
    align: 'center' as const,
  },
  attribution: {
    x: 0.5,
    y: 5.0,
    w: 9.0,
    h: 0.4,
    fontSize: FONT_SIZES.caption,
    fontFace: FONTS.body,
    color: PPTX_COLORS.slate,
    italic: true,
    align: 'center' as const,
  },
} as const;

/**
 * Section header slide styles
 */
export const SECTION_SLIDE_STYLE = {
  title: {
    x: 0.5,
    y: 2.2,
    w: 9.0,
    h: 1.2,
    fontSize: FONT_SIZES.heading,
    fontFace: FONTS.heading,
    color: PPTX_COLORS.white,
    bold: true,
    align: 'center' as const,
  },
  background: PPTX_COLORS.navy,
} as const;

/**
 * Content slide styles
 */
export const CONTENT_SLIDE_STYLE = {
  title: {
    x: 0.5,
    y: 0.3,
    w: 9.0,
    h: 0.6,
    fontSize: FONT_SIZES.heading,
    fontFace: FONTS.heading,
    color: PPTX_COLORS.navy,
    bold: true,
    align: 'left' as const,
  },
  body: {
    x: 0.5,
    y: 1.0,
    w: 9.0,
    h: 4.0,
    fontSize: FONT_SIZES.body,
    fontFace: FONTS.body,
    color: PPTX_COLORS.slate,
    align: 'left' as const,
    valign: 'top' as const,
  },
} as const;

/**
 * Two-column layout styles
 */
export const TWO_COLUMN_STYLE = {
  leftColumn: {
    x: 0.5,
    y: 1.0,
    w: 4.25,
    h: 4.0,
  },
  rightColumn: {
    x: 5.0,
    y: 1.0,
    w: 4.25,
    h: 4.0,
  },
} as const;

/**
 * Metric box styles for key metrics display
 */
export const METRIC_BOX_STYLE = {
  box: {
    fill: { color: PPTX_COLORS.lightGray },
    line: { color: PPTX_COLORS.mediumGray, width: 1 },
  },
  label: {
    fontSize: FONT_SIZES.small,
    fontFace: FONTS.body,
    color: PPTX_COLORS.slate,
    bold: false,
  },
  value: {
    fontSize: FONT_SIZES.heading,
    fontFace: FONTS.heading,
    color: PPTX_COLORS.navy,
    bold: true,
  },
  highlight: {
    fontSize: FONT_SIZES.title,
    fontFace: FONTS.heading,
    color: PPTX_COLORS.gold,
    bold: true,
  },
} as const;

/**
 * Table styles
 */
export const TABLE_STYLE = {
  header: {
    fill: { color: PPTX_COLORS.navy },
    color: PPTX_COLORS.white,
    bold: true,
    fontSize: FONT_SIZES.small,
    fontFace: FONTS.body,
    align: 'center' as const,
  },
  body: {
    fill: { color: PPTX_COLORS.white },
    color: PPTX_COLORS.slate,
    fontSize: FONT_SIZES.small,
    fontFace: FONTS.body,
    align: 'left' as const,
  },
  altRow: {
    fill: { color: PPTX_COLORS.lightGray },
    color: PPTX_COLORS.slate,
    fontSize: FONT_SIZES.small,
    fontFace: FONTS.body,
    align: 'left' as const,
  },
  border: {
    color: PPTX_COLORS.mediumGray,
    pt: 0.5,
  },
} as const;

/**
 * Chart styles
 */
export const CHART_STYLE = {
  colors: [
    PPTX_COLORS.navy,
    PPTX_COLORS.gold,
    PPTX_COLORS.green,
    PPTX_COLORS.slate,
    PPTX_COLORS.amber,
    PPTX_COLORS.red,
  ],
  title: {
    fontSize: FONT_SIZES.subheading,
    fontFace: FONTS.heading,
    color: PPTX_COLORS.navy,
    bold: true,
  },
  legend: {
    fontSize: FONT_SIZES.small,
    fontFace: FONTS.body,
    color: PPTX_COLORS.slate,
  },
} as const;

/**
 * Footer styles
 */
export const FOOTER_STYLE = {
  text: {
    x: 0.5,
    y: 5.3,
    w: 9.0,
    h: 0.25,
    fontSize: FONT_SIZES.caption,
    fontFace: FONTS.body,
    color: PPTX_COLORS.slate,
    italic: true,
    align: 'center' as const,
  },
} as const;

/**
 * Get score-based color
 */
export function getScoreColor(score: number): string {
  if (score >= 80) return PPTX_COLORS.green;
  if (score >= 60) return PPTX_COLORS.gold;
  if (score >= 40) return PPTX_COLORS.amber;
  return PPTX_COLORS.red;
}

/**
 * Get score interpretation text
 */
export function getScoreInterpretation(score: number): string {
  if (score >= 80) return 'Strong';
  if (score >= 60) return 'Good';
  if (score >= 40) return 'Needs Improvement';
  return 'Critical';
}

/**
 * Format currency for display
 */
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

/**
 * Format percentage for display
 */
export function formatPercent(value: number, decimals: number = 1): string {
  return `${value.toFixed(decimals)}%`;
}

/**
 * Format score for display
 */
export function formatScore(score: number): string {
  return `${Math.round(score)}/100`;
}
