/**
 * PDF Document Styles
 *
 * Consistent styling for PDF documents generated by the platform.
 * Uses "Executive Clarity" theme - Navy primary, Gold accents.
 *
 * Story 18.4: PowerPoint & PDF Generation
 * Task 3.2: Create PDF style constants
 * Covers: NFR28 (Board-presentation ready)
 */

import { StyleSheet } from '@react-pdf/renderer';

/**
 * Brand colors for PDF
 */
export const PDF_COLORS = {
  navy: '#0F172A',
  slate: '#334155',
  gold: '#D97706',
  lightGray: '#F1F5F9',
  mediumGray: '#E2E8F0',
  white: '#FFFFFF',
  red: '#DC2626',
  green: '#16A34A',
  amber: '#F59E0B',
} as const;

/**
 * Attribution text for book reference
 */
export const ATTRIBUTION_TEXT =
  'Based on The Last Paradigm methodology | thelastparadigm.com';

/**
 * Standard font sizes
 */
export const FONT_SIZES = {
  title: 28,
  heading1: 20,
  heading2: 16,
  heading3: 14,
  body: 11,
  small: 9,
  caption: 8,
} as const;

/**
 * Page dimensions (US Letter)
 */
export const PAGE_DIMENSIONS = {
  width: 612, // points (8.5 inches)
  height: 792, // points (11 inches)
} as const;

/**
 * Standard margins
 */
export const MARGINS = {
  top: 72, // 1 inch
  bottom: 72,
  left: 72,
  right: 72,
} as const;

/**
 * Common PDF styles using StyleSheet
 */
export const pdfStyles = StyleSheet.create({
  // Page styles
  page: {
    paddingTop: MARGINS.top,
    paddingBottom: MARGINS.bottom,
    paddingLeft: MARGINS.left,
    paddingRight: MARGINS.right,
    fontFamily: 'Helvetica',
    fontSize: FONT_SIZES.body,
    color: PDF_COLORS.slate,
  },

  // Cover page styles
  coverPage: {
    paddingTop: 200,
    paddingBottom: MARGINS.bottom,
    paddingLeft: MARGINS.left,
    paddingRight: MARGINS.right,
    backgroundColor: PDF_COLORS.navy,
  },

  coverTitle: {
    fontSize: FONT_SIZES.title,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.white,
    textAlign: 'center',
    marginBottom: 20,
  },

  coverSubtitle: {
    fontSize: FONT_SIZES.heading2,
    color: PDF_COLORS.lightGray,
    textAlign: 'center',
    marginBottom: 40,
  },

  coverAttribution: {
    fontSize: FONT_SIZES.small,
    color: PDF_COLORS.slate,
    textAlign: 'center',
    position: 'absolute',
    bottom: 72,
    left: 72,
    right: 72,
  },

  // Heading styles
  heading1: {
    fontSize: FONT_SIZES.heading1,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.navy,
    marginBottom: 16,
    marginTop: 24,
  },

  heading2: {
    fontSize: FONT_SIZES.heading2,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.navy,
    marginBottom: 12,
    marginTop: 20,
  },

  heading3: {
    fontSize: FONT_SIZES.heading3,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.slate,
    marginBottom: 8,
    marginTop: 16,
  },

  // Body text
  body: {
    fontSize: FONT_SIZES.body,
    color: PDF_COLORS.slate,
    lineHeight: 1.5,
    marginBottom: 8,
  },

  bodyBold: {
    fontSize: FONT_SIZES.body,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.slate,
    marginBottom: 8,
  },

  // Small text
  small: {
    fontSize: FONT_SIZES.small,
    color: PDF_COLORS.slate,
  },

  caption: {
    fontSize: FONT_SIZES.caption,
    color: PDF_COLORS.slate,
    fontStyle: 'italic',
  },

  // Highlight/metric styles
  metricValue: {
    fontSize: FONT_SIZES.heading1,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.navy,
  },

  metricValueHighlight: {
    fontSize: FONT_SIZES.heading1,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.gold,
  },

  metricLabel: {
    fontSize: FONT_SIZES.small,
    color: PDF_COLORS.slate,
    marginTop: 4,
  },

  metricLabelHighlight: {
    fontSize: FONT_SIZES.small,
    color: PDF_COLORS.lightGray,
    marginTop: 4,
  },

  // Table styles
  table: {
    width: '100%',
    marginVertical: 12,
  },

  tableHeader: {
    flexDirection: 'row',
    backgroundColor: PDF_COLORS.navy,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },

  tableHeaderCell: {
    fontSize: FONT_SIZES.small,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.white,
    flex: 1,
  },

  tableRow: {
    flexDirection: 'row',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.mediumGray,
  },

  tableRowAlt: {
    flexDirection: 'row',
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: PDF_COLORS.lightGray,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.mediumGray,
  },

  tableCell: {
    fontSize: FONT_SIZES.small,
    color: PDF_COLORS.slate,
    flex: 1,
  },

  // Bullet list
  bulletList: {
    marginLeft: 20,
    marginBottom: 12,
  },

  bulletItem: {
    flexDirection: 'row',
    marginBottom: 6,
  },

  bulletPoint: {
    width: 15,
    fontSize: FONT_SIZES.body,
    color: PDF_COLORS.gold,
  },

  bulletText: {
    flex: 1,
    fontSize: FONT_SIZES.body,
    color: PDF_COLORS.slate,
    lineHeight: 1.4,
  },

  // Key-value pairs
  keyValueRow: {
    flexDirection: 'row',
    marginBottom: 6,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.lightGray,
  },

  keyValueLabel: {
    width: '40%',
    fontSize: FONT_SIZES.body,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.slate,
  },

  keyValueValue: {
    width: '60%',
    fontSize: FONT_SIZES.body,
    color: PDF_COLORS.navy,
  },

  // Metric box
  metricBox: {
    backgroundColor: PDF_COLORS.lightGray,
    padding: 16,
    marginBottom: 12,
    borderRadius: 4,
  },

  metricBoxHighlight: {
    backgroundColor: PDF_COLORS.navy,
    padding: 16,
    marginBottom: 12,
    borderRadius: 4,
  },

  // Header/Footer
  header: {
    position: 'absolute',
    top: 30,
    left: MARGINS.left,
    right: MARGINS.right,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.mediumGray,
    paddingBottom: 8,
  },

  headerText: {
    fontSize: FONT_SIZES.caption,
    color: PDF_COLORS.slate,
  },

  footer: {
    position: 'absolute',
    bottom: 30,
    left: MARGINS.left,
    right: MARGINS.right,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: PDF_COLORS.mediumGray,
    paddingTop: 8,
  },

  footerText: {
    fontSize: FONT_SIZES.caption,
    color: PDF_COLORS.slate,
  },

  pageNumber: {
    fontSize: FONT_SIZES.caption,
    color: PDF_COLORS.slate,
  },

  // Divider
  divider: {
    borderBottomWidth: 2,
    borderBottomColor: PDF_COLORS.gold,
    marginVertical: 20,
    width: 60,
  },

  // Score indicator
  scoreIndicator: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },

  scoreText: {
    fontSize: FONT_SIZES.heading3,
    fontFamily: 'Helvetica-Bold',
    color: PDF_COLORS.white,
    textAlign: 'center',
  },

  // Layout helpers
  row: {
    flexDirection: 'row',
  },

  column: {
    flexDirection: 'column',
  },

  spacer: {
    height: 20,
  },

  flex1: {
    flex: 1,
  },

  flexGrow: {
    flexGrow: 1,
  },
});

/**
 * Get score-based color
 */
export function getScoreColor(score: number): string {
  if (score >= 80) return PDF_COLORS.green;
  if (score >= 60) return PDF_COLORS.gold;
  if (score >= 40) return PDF_COLORS.amber;
  return PDF_COLORS.red;
}

/**
 * Get score interpretation text
 */
export function getScoreInterpretation(score: number): string {
  if (score >= 80) return 'Strong';
  if (score >= 60) return 'Good';
  if (score >= 40) return 'Needs Improvement';
  return 'Critical';
}

/**
 * Format currency for display
 */
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

/**
 * Format percentage for display
 */
export function formatPercent(value: number, decimals: number = 1): string {
  return `${value.toFixed(decimals)}%`;
}

/**
 * Format score for display
 */
export function formatScore(score: number): string {
  return `${Math.round(score)}/100`;
}
