/**
 * Excel Document Styles
 *
 * Consistent styling for all Excel documents generated by the platform.
 * Uses "Executive Clarity" theme - Navy primary, Gold accents.
 *
 * Story 18.3: Excel Document Templates & Generation
 * Task 1.3: Create Excel style constants
 * Covers: NFR28 (Board-presentation ready)
 */

import type { Style, Fill, Font, Border, Alignment } from 'exceljs';

/**
 * Brand colors in ARGB format for Excel
 */
export const EXCEL_COLORS = {
  navy: 'FF0F172A',
  slate: 'FF334155',
  gold: 'FFD97706',
  lightGray: 'FFF1F5F9',
  mediumGray: 'FFE2E8F0',
  white: 'FFFFFFFF',
  red: 'FFDC2626',
  green: 'FF16A34A',
  amber: 'FFF59E0B',
} as const;

/**
 * Attribution text for book reference
 */
export const ATTRIBUTION_TEXT =
  'Based on The Last Paradigm methodology | thelastparadigm.com';

/**
 * Standard header style for tables
 */
export const HEADER_STYLE: Partial<Style> = {
  font: {
    bold: true,
    size: 11,
    color: { argb: EXCEL_COLORS.white },
    name: 'Calibri',
  },
  fill: {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: EXCEL_COLORS.navy },
  } as Fill,
  alignment: {
    horizontal: 'center',
    vertical: 'middle',
    wrapText: true,
  },
  border: {
    top: { style: 'thin', color: { argb: EXCEL_COLORS.slate } },
    bottom: { style: 'thin', color: { argb: EXCEL_COLORS.slate } },
    left: { style: 'thin', color: { argb: EXCEL_COLORS.slate } },
    right: { style: 'thin', color: { argb: EXCEL_COLORS.slate } },
  },
};

/**
 * Style for data cells
 */
export const DATA_CELL_STYLE: Partial<Style> = {
  font: {
    size: 10,
    color: { argb: EXCEL_COLORS.slate },
    name: 'Calibri',
  },
  alignment: {
    vertical: 'middle',
  },
  border: {
    top: { style: 'thin', color: { argb: EXCEL_COLORS.mediumGray } },
    bottom: { style: 'thin', color: { argb: EXCEL_COLORS.mediumGray } },
    left: { style: 'thin', color: { argb: EXCEL_COLORS.mediumGray } },
    right: { style: 'thin', color: { argb: EXCEL_COLORS.mediumGray } },
  },
};

/**
 * Style for alternating row (zebra striping)
 */
export const ALT_ROW_STYLE: Partial<Style> = {
  ...DATA_CELL_STYLE,
  fill: {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: EXCEL_COLORS.lightGray },
  } as Fill,
};

/**
 * Style for title cells
 */
export const TITLE_STYLE: Partial<Style> = {
  font: {
    bold: true,
    size: 18,
    color: { argb: EXCEL_COLORS.navy },
    name: 'Calibri',
  },
  alignment: {
    horizontal: 'left',
    vertical: 'middle',
  },
};

/**
 * Style for section headers
 */
export const SECTION_HEADER_STYLE: Partial<Style> = {
  font: {
    bold: true,
    size: 14,
    color: { argb: EXCEL_COLORS.navy },
    name: 'Calibri',
  },
  alignment: {
    horizontal: 'left',
    vertical: 'middle',
  },
};

/**
 * Style for highlighted/important values
 */
export const HIGHLIGHT_STYLE: Partial<Style> = {
  font: {
    bold: true,
    size: 14,
    color: { argb: EXCEL_COLORS.gold },
    name: 'Calibri',
  },
  alignment: {
    horizontal: 'right',
    vertical: 'middle',
  },
};

/**
 * Style for currency values
 */
export const CURRENCY_STYLE: Partial<Style> = {
  ...DATA_CELL_STYLE,
  numFmt: '$#,##0',
  alignment: {
    horizontal: 'right',
    vertical: 'middle',
  },
};

/**
 * Style for percentage values
 */
export const PERCENT_STYLE: Partial<Style> = {
  ...DATA_CELL_STYLE,
  numFmt: '0.0%',
  alignment: {
    horizontal: 'right',
    vertical: 'middle',
  },
};

/**
 * Style for number values
 */
export const NUMBER_STYLE: Partial<Style> = {
  ...DATA_CELL_STYLE,
  numFmt: '#,##0',
  alignment: {
    horizontal: 'right',
    vertical: 'middle',
  },
};

/**
 * Style for date values
 */
export const DATE_STYLE: Partial<Style> = {
  ...DATA_CELL_STYLE,
  numFmt: 'mm/dd/yyyy',
  alignment: {
    horizontal: 'center',
    vertical: 'middle',
  },
};

/**
 * Style for formula input cells (editable by user)
 */
export const INPUT_CELL_STYLE: Partial<Style> = {
  font: {
    size: 10,
    color: { argb: EXCEL_COLORS.navy },
    name: 'Calibri',
  },
  fill: {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFFFF8E1' }, // Light yellow to indicate editable
  } as Fill,
  border: {
    top: { style: 'thin', color: { argb: EXCEL_COLORS.gold } },
    bottom: { style: 'thin', color: { argb: EXCEL_COLORS.gold } },
    left: { style: 'thin', color: { argb: EXCEL_COLORS.gold } },
    right: { style: 'thin', color: { argb: EXCEL_COLORS.gold } },
  },
  alignment: {
    horizontal: 'right',
    vertical: 'middle',
  },
};

/**
 * Style for attribution footer
 */
export const ATTRIBUTION_STYLE: Partial<Style> = {
  font: {
    italic: true,
    size: 9,
    color: { argb: EXCEL_COLORS.slate },
    name: 'Calibri',
  },
  alignment: {
    horizontal: 'center',
    vertical: 'middle',
  },
};

/**
 * Get conditional formatting color based on score
 */
export function getScoreColor(score: number): string {
  if (score >= 80) return EXCEL_COLORS.green;
  if (score >= 60) return EXCEL_COLORS.gold;
  if (score >= 40) return EXCEL_COLORS.amber;
  return EXCEL_COLORS.red;
}

/**
 * Standard column widths
 */
export const COLUMN_WIDTHS = {
  narrow: 10,
  medium: 15,
  wide: 25,
  extraWide: 40,
} as const;

/**
 * Standard row heights
 */
export const ROW_HEIGHTS = {
  header: 25,
  data: 20,
  title: 30,
  spacer: 10,
} as const;
