/**
 * Tests for PdfFooter PDF Component
 *
 * Verifies that branding, attribution, and page numbers are displayed correctly.
 *
 * Note: @react-pdf/renderer uses custom primitives that don't render to DOM.
 * Tests verify component can be instantiated correctly.
 *
 * Covers: FR27 (branding and attribution in PDF)
 */

import { describe, it, expect, vi } from 'vitest';
import { render } from '@testing-library/react';

// Mock @react-pdf/renderer to prevent actual PDF rendering in tests
vi.mock('@react-pdf/renderer', () => ({
  View: ({ children }: { children: React.ReactNode }) => children,
  Text: ({ children }: { children: React.ReactNode }) => children,
  StyleSheet: {
    create: (styles: Record<string, unknown>) => styles,
  },
}));

// Import after mocking
import { PdfFooter } from './PdfFooter';

describe('PdfFooter', () => {
  describe('Component Rendering', () => {
    it('renders without crashing', () => {
      expect(() => {
        render(<PdfFooter />);
      }).not.toThrow();
    });

    it('returns defined container', () => {
      const { container } = render(<PdfFooter />);
      expect(container).toBeDefined();
    });
  });

  describe('Component Definition', () => {
    it('is a function component', () => {
      expect(typeof PdfFooter).toBe('function');
    });

    it('exports as named export', () => {
      expect(PdfFooter).toBeDefined();
      expect(PdfFooter.name).toBe('PdfFooter');
    });
  });

  describe('Branding and Attribution', () => {
    it('renders with no props (branding content is static)', () => {
      // Component contains:
      // - "Generated by The Last Paradigm Platform"
      // - "Based on methodology from 'The Last Paradigm' by Matt Keane"
      // - Copyright notice with 2026
      expect(() => render(<PdfFooter />)).not.toThrow();
    });
  });

  describe('Page Numbers', () => {
    it('accepts optional pageNumber prop', () => {
      expect(() => {
        render(<PdfFooter pageNumber={1} totalPages={3} />);
      }).not.toThrow();
    });

    it('renders without page numbers when not provided', () => {
      expect(() => {
        render(<PdfFooter />);
      }).not.toThrow();
    });

    it('handles different page numbers', () => {
      expect(() => {
        render(<PdfFooter pageNumber={1} totalPages={4} />);
        render(<PdfFooter pageNumber={2} totalPages={4} />);
        render(<PdfFooter pageNumber={3} totalPages={4} />);
        render(<PdfFooter pageNumber={4} totalPages={4} />);
      }).not.toThrow();
    });
  });

  describe('Edge Cases', () => {
    it('handles page number without total pages', () => {
      // When only pageNumber is provided without totalPages,
      // the component should still render without crashing
      expect(() => {
        render(<PdfFooter pageNumber={1} />);
      }).not.toThrow();
    });

    it('handles total pages without page number', () => {
      expect(() => {
        render(<PdfFooter totalPages={5} />);
      }).not.toThrow();
    });
  });
});
