/**
 * PDF Footer Component
 *
 * Displays The Last Paradigm branding, attribution, and page numbers
 * at the bottom of each PDF page.
 *
 * Covers: FR27 (branding and attribution in PDF)
 */

'use client';

import { View, Text } from '@react-pdf/renderer';
import { pdfStyles, pdfColors } from '../PdfStyles';
import { StyleSheet } from '@react-pdf/renderer';

interface PdfFooterProps {
  /** Current page number */
  pageNumber?: number;
  /** Total number of pages */
  totalPages?: number;
}

// Additional styles specific to this section
const localStyles = StyleSheet.create({
  footerContainer: {
    position: 'absolute',
    bottom: 40,
    left: 72,
    right: 72,
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    paddingTop: 12,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandSection: {
    flexDirection: 'column',
  },
  brandName: {
    fontSize: 9,
    fontWeight: 700,
    color: pdfColors.navy,
    marginBottom: 2,
  },
  attribution: {
    fontSize: 8,
    color: pdfColors.muted,
    marginBottom: 2,
  },
  copyright: {
    fontSize: 8,
    color: pdfColors.muted,
  },
  pageNumber: {
    fontSize: 9,
    color: pdfColors.muted,
  },
});

export function PdfFooter({ pageNumber, totalPages }: PdfFooterProps) {
  return (
    <View style={localStyles.footerContainer} fixed>
      <View style={localStyles.footerRow}>
        <View style={localStyles.brandSection}>
          <Text style={localStyles.brandName}>
            Generated by The Last Paradigm Platform
          </Text>
          <Text style={localStyles.attribution}>
            Based on methodology from &quot;The Last Paradigm&quot; by Matt Keane
          </Text>
          <Text style={localStyles.copyright}>
            {'\u00A9'} 2026 The Last Paradigm. All rights reserved.
          </Text>
        </View>
        {pageNumber !== undefined && totalPages !== undefined && (
          <Text style={localStyles.pageNumber}>
            Page {pageNumber} of {totalPages}
          </Text>
        )}
      </View>
    </View>
  );
}
