/**
 * Word Document Brand Styles
 *
 * Consistent styling for all Word documents generated by the platform.
 * Uses "Executive Clarity" theme - Navy primary, Gold accents.
 *
 * Story 18.2: Word Document Templates & Generation
 * Task 1.3: Create brand style constants
 * Covers: NFR28 (Board-presentation ready)
 */

import { convertInchesToTwip } from 'docx';

/**
 * Brand color palette (hex without #)
 */
export const BRAND_COLORS = {
  navy: '0F172A', // Primary text, headers
  slate: '334155', // Secondary text
  gold: 'D97706', // Accents, highlights
  lightGray: 'F1F5F9', // Table backgrounds
  mediumGray: 'E2E8F0', // Borders
  white: 'FFFFFF',
  red: 'DC2626', // Warnings, critical
  green: '16A34A', // Success, positive
  amber: 'F59E0B', // Caution
} as const;

/**
 * Brand fonts
 */
export const BRAND_FONTS = {
  heading: 'Calibri',
  body: 'Calibri',
  mono: 'Consolas',
} as const;

/**
 * Document text styles (size in half-points, e.g., 24 = 12pt)
 */
export const DOCUMENT_STYLES = {
  title: {
    font: BRAND_FONTS.heading,
    size: 48, // 24pt
    bold: true,
    color: BRAND_COLORS.navy,
  },
  heading1: {
    font: BRAND_FONTS.heading,
    size: 36, // 18pt
    bold: true,
    color: BRAND_COLORS.navy,
  },
  heading2: {
    font: BRAND_FONTS.heading,
    size: 28, // 14pt
    bold: true,
    color: BRAND_COLORS.slate,
  },
  heading3: {
    font: BRAND_FONTS.heading,
    size: 24, // 12pt
    bold: true,
    color: BRAND_COLORS.slate,
  },
  body: {
    font: BRAND_FONTS.body,
    size: 22, // 11pt
    color: BRAND_COLORS.slate,
  },
  bodySmall: {
    font: BRAND_FONTS.body,
    size: 18, // 9pt
    color: BRAND_COLORS.slate,
  },
  highlight: {
    font: BRAND_FONTS.body,
    size: 28, // 14pt
    bold: true,
    color: BRAND_COLORS.gold,
  },
  highlightLarge: {
    font: BRAND_FONTS.body,
    size: 36, // 18pt
    bold: true,
    color: BRAND_COLORS.gold,
  },
  tableHeader: {
    font: BRAND_FONTS.body,
    size: 22, // 11pt
    bold: true,
    color: BRAND_COLORS.white,
  },
  tableCell: {
    font: BRAND_FONTS.body,
    size: 20, // 10pt
    color: BRAND_COLORS.slate,
  },
} as const;

/**
 * Page margins in twips (1 inch = 1440 twips)
 */
export const PAGE_MARGINS = {
  top: convertInchesToTwip(1),
  bottom: convertInchesToTwip(1),
  left: convertInchesToTwip(1.25),
  right: convertInchesToTwip(1.25),
} as const;

/**
 * Spacing constants in twips
 */
export const SPACING = {
  sectionBefore: 400,
  sectionAfter: 200,
  paragraphAfter: 120,
  listItemAfter: 80,
  tableRowHeight: 400,
} as const;

/**
 * Score interpretation thresholds
 */
export const SCORE_THRESHOLDS = {
  excellent: 80,
  good: 60,
  moderate: 40,
  poor: 20,
} as const;

/**
 * Get color based on score (higher is better)
 */
export function getScoreColor(score: number): string {
  if (score >= SCORE_THRESHOLDS.excellent) return BRAND_COLORS.green;
  if (score >= SCORE_THRESHOLDS.good) return BRAND_COLORS.gold;
  if (score >= SCORE_THRESHOLDS.moderate) return BRAND_COLORS.amber;
  return BRAND_COLORS.red;
}

/**
 * Get interpretation text based on score
 */
export function getScoreInterpretation(score: number): string {
  if (score >= SCORE_THRESHOLDS.excellent) return 'Excellent';
  if (score >= SCORE_THRESHOLDS.good) return 'Good';
  if (score >= SCORE_THRESHOLDS.moderate) return 'Needs Improvement';
  if (score >= SCORE_THRESHOLDS.poor) return 'Critical';
  return 'Severe';
}
