/**
 * Diagnostic PDF Document Component
 *
 * Main document structure for the Complete Diagnostic PDF Export.
 * Combines all sections into a professional, board-room quality PDF.
 *
 * Story 14.6: Complete Diagnostic PDF Export
 * Covers: FR2-36 (Export full 7-tool diagnostic as premium PDF)
 *
 * Document Structure:
 * 1. Cover Page - Branding, headline number
 * 2. Executive Summary - Interpretation, key findings
 * 3. Tool Results - Summaries from all 6 diagnostic tools
 * 4. Cost Breakdown - Detailed cost table and distribution
 * 5. ROI Projections - Investment return scenarios (if available)
 * 6. Recommendations - Prioritized action items
 * 7. Methodology - How the analysis was performed
 */

'use client';

import { Document, Page, View, Text } from '@react-pdf/renderer';
import {
  diagnosticPDFStyles as styles,
  brandColors,
  formatDatePDF,
} from './DiagnosticPDFStyles';
import { PDFCoverPage } from './PDFCoverPage';
import { PDFExecutiveSummary } from './PDFExecutiveSummary';
import { PDFAllToolsSummary } from './PDFToolSummary';
import { PDFCostBreakdown } from './PDFCostBreakdown';
import { PDFROISummary, PDFROIPlaceholder } from './PDFROISummary';
import { PDFRecommendations } from './PDFRecommendations';
import type {
  AlignmentTaxResult,
  AggregatedToolData,
  ROIResult,
} from '../cost-constants';

/**
 * Props for the Diagnostic PDF Document
 */
export interface DiagnosticPDFDocumentProps {
  /** Alignment tax calculation result */
  result: AlignmentTaxResult;
  /** Aggregated data from all diagnostic tools */
  aggregatedData: AggregatedToolData;
  /** Organization name (optional) */
  organizationName?: string;
  /** ROI calculation results (optional - from Story 14.5) */
  roiResults?: ROIResult[];
  /** Investment amount for ROI (optional) */
  investment?: number;
}

/**
 * PDF Header Component for regular pages
 */
function PDFHeader({ title }: { title?: string }) {
  return (
    <View style={styles.header}>
      <Text style={styles.headerBrand}>The Last Paradigm</Text>
      <Text style={styles.headerTitle}>
        {title || 'Complete Alignment Diagnostic'}
      </Text>
    </View>
  );
}

/**
 * PDF Footer Component for regular pages
 */
function PDFFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>
        Generated by The Last Paradigm Platform
      </Text>
      <Text
        style={styles.pageNumber}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}

/**
 * Methodology Section
 */
function MethodologySection() {
  return (
    <View style={styles.section}>
      <Text style={styles.pageTitle}>Methodology</Text>
      <Text style={styles.body}>
        This diagnostic assessment uses a rigorous methodology developed through
        extensive research into organizational effectiveness and alignment.
      </Text>

      <View style={styles.sectionWithBackground}>
        <Text style={styles.subHeader}>The 7-Tool Framework</Text>
        <Text style={styles.bodySmall}>
          The alignment tax is calculated using data from up to 7 complementary
          diagnostic tools, each measuring a different dimension of
          organizational alignment:
        </Text>

        <View style={{ marginTop: 10 }}>
          <View style={styles.costCategoryRow}>
            <Text style={[styles.costCategoryName, { flex: 1 }]}>
              1. Alignment Assessment
            </Text>
            <Text style={[styles.bodySmall, { flex: 2 }]}>
              Measures alignment across 5 key dimensions
            </Text>
          </View>
          <View style={styles.costCategoryRow}>
            <Text style={[styles.costCategoryName, { flex: 1 }]}>
              2. Meeting Audit
            </Text>
            <Text style={[styles.bodySmall, { flex: 2 }]}>
              Quantifies meeting waste costs
            </Text>
          </View>
          <View style={styles.costCategoryRow}>
            <Text style={[styles.costCategoryName, { flex: 1 }]}>
              3. Decision Velocity
            </Text>
            <Text style={[styles.bodySmall, { flex: 2 }]}>
              Measures decision-making speed and bottlenecks
            </Text>
          </View>
          <View style={styles.costCategoryRow}>
            <Text style={[styles.costCategoryName, { flex: 1 }]}>
              4. Stakeholder Map
            </Text>
            <Text style={[styles.bodySmall, { flex: 2 }]}>
              Identifies key players and potential blockers
            </Text>
          </View>
          <View style={styles.costCategoryRow}>
            <Text style={[styles.costCategoryName, { flex: 1 }]}>
              5. Data Flow Analysis
            </Text>
            <Text style={[styles.bodySmall, { flex: 2 }]}>
              Quantifies data friction costs
            </Text>
          </View>
          <View style={styles.costCategoryRow}>
            <Text style={[styles.costCategoryName, { flex: 1 }]}>
              6. Communication Diagnostic
            </Text>
            <Text style={[styles.bodySmall, { flex: 2 }]}>
              Detects communication anti-patterns
            </Text>
          </View>
          <View style={styles.costCategoryRow}>
            <Text style={[styles.costCategoryName, { flex: 1 }]}>
              7. Total Cost Calculator
            </Text>
            <Text style={[styles.bodySmall, { flex: 2 }]}>
              Aggregates all costs into alignment tax
            </Text>
          </View>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.subHeader}>Interpretation Thresholds</Text>
        <Text style={styles.body}>
          The alignment tax as a percentage of revenue is compared against
          industry benchmarks:
        </Text>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.tableHeaderCell}>Level</Text>
            <Text style={styles.tableHeaderCell}>% of Revenue</Text>
            <Text style={[styles.tableHeaderCell, { flex: 2 }]}>Implication</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={[styles.tableCell, { color: '#059669' }]}>Normal</Text>
            <Text style={styles.tableCell}>&lt; 2%</Text>
            <Text style={[styles.tableCell, { flex: 2 }]}>Typical range, continuous improvement</Text>
          </View>
          <View style={styles.tableRowAlt}>
            <Text style={[styles.tableCell, { color: '#d97706' }]}>Significant</Text>
            <Text style={styles.tableCell}>2-4%</Text>
            <Text style={[styles.tableCell, { flex: 2 }]}>Above average, warrants attention</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={[styles.tableCell, { color: '#ea580c' }]}>Crisis</Text>
            <Text style={styles.tableCell}>4-7%</Text>
            <Text style={[styles.tableCell, { flex: 2 }]}>Requires immediate intervention</Text>
          </View>
          <View style={styles.tableRowAlt}>
            <Text style={[styles.tableCell, { color: '#dc2626' }]}>Existential</Text>
            <Text style={styles.tableCell}>&gt; 7%</Text>
            <Text style={[styles.tableCell, { flex: 2 }]}>Threatens organizational viability</Text>
          </View>
        </View>
      </View>

      <View style={styles.callout}>
        <Text style={styles.calloutText}>
          The methodology is based on research presented in "The Last Paradigm"
          and refined through application with hundreds of organizations.
          Results should be validated with internal data and used as a starting
          point for deeper analysis.
        </Text>
      </View>
    </View>
  );
}

/**
 * Final CTA Page
 */
function CTASection() {
  return (
    <View style={styles.section}>
      <Text style={styles.pageTitle}>Next Steps</Text>

      <View style={styles.ctaBox}>
        <Text style={styles.ctaTitle}>Ready to Transform?</Text>
        <Text style={styles.ctaText}>
          Understanding your alignment tax is the first step. The Last Paradigm
          provides expert guidance to help organizations reduce their alignment
          tax and achieve operational excellence.
        </Text>
        <Text style={styles.ctaUrl}>thelastparadigm.com</Text>
      </View>

      <View style={{ marginTop: 30 }}>
        <Text style={styles.subHeader}>About This Report</Text>
        <Text style={styles.body}>
          This report was generated by The Last Paradigm Platform, a
          comprehensive diagnostic suite for measuring and addressing
          organizational misalignment.
        </Text>
        <Text style={styles.body}>
          For questions about this report or to discuss transformation
          strategies, please contact us.
        </Text>
      </View>

      <View style={{ marginTop: 20 }}>
        <Text style={styles.label}>CONFIDENTIALITY NOTICE</Text>
        <Text style={styles.bodySmall}>
          This document contains confidential assessment data and is intended
          solely for the organization that commissioned this diagnostic. Do not
          distribute without authorization.
        </Text>
      </View>
    </View>
  );
}

/**
 * Diagnostic PDF Document
 *
 * Main document component that renders the complete diagnostic PDF.
 * Generates a multi-page, board-room quality report in < 10 seconds.
 */
export function DiagnosticPDFDocument({
  result,
  aggregatedData,
  organizationName,
  roiResults,
  investment,
}: DiagnosticPDFDocumentProps) {
  const toolsCompleted = aggregatedData.completedToolsCount;
  const generatedAt = new Date().toISOString();

  return (
    <Document
      title="Complete Alignment Diagnostic Report"
      author="The Last Paradigm"
      subject="Organizational Alignment Tax Analysis"
      creator="The Last Paradigm Platform"
      keywords="alignment tax, organizational effectiveness, diagnostic"
    >
      {/* Page 1: Cover */}
      <PDFCoverPage
        organizationName={organizationName}
        generatedAt={generatedAt}
        totalAlignmentTax={result.total}
        toolsCompleted={toolsCompleted}
      />

      {/* Page 2: Executive Summary */}
      <Page size="LETTER" style={styles.page}>
        <PDFHeader title="Executive Summary" />
        <PDFExecutiveSummary result={result} toolsCompleted={toolsCompleted} />
        <PDFFooter />
      </Page>

      {/* Page 3: Tool Results */}
      <Page size="LETTER" style={styles.page}>
        <PDFHeader title="Tool Results" />
        <PDFAllToolsSummary data={aggregatedData} />
        <PDFFooter />
      </Page>

      {/* Page 4: Cost Breakdown */}
      <Page size="LETTER" style={styles.page}>
        <PDFHeader title="Cost Breakdown" />
        <PDFCostBreakdown result={result} />
        <PDFFooter />
      </Page>

      {/* Page 5: ROI Projections */}
      <Page size="LETTER" style={styles.page}>
        <PDFHeader title="ROI Projections" />
        {roiResults && roiResults.length > 0 && investment ? (
          <PDFROISummary
            alignmentTax={result.total}
            investment={investment}
            results={roiResults}
          />
        ) : (
          <PDFROIPlaceholder alignmentTax={result.total} />
        )}
        <PDFFooter />
      </Page>

      {/* Page 6: Recommendations */}
      <Page size="LETTER" style={styles.page}>
        <PDFHeader title="Recommendations" />
        <PDFRecommendations result={result} aggregatedData={aggregatedData} />
        <PDFFooter />
      </Page>

      {/* Page 7: Methodology */}
      <Page size="LETTER" style={styles.page}>
        <PDFHeader title="Methodology" />
        <MethodologySection />
        <PDFFooter />
      </Page>

      {/* Page 8: Next Steps / CTA */}
      <Page size="LETTER" style={styles.page}>
        <PDFHeader title="Next Steps" />
        <CTASection />
        <PDFFooter />
      </Page>
    </Document>
  );
}
