/**
 * Excel Template Parser
 *
 * Parses and validates uploaded Excel templates to extract meeting audit data.
 * Validates data integrity before populating the calculator form.
 *
 * Covers: FR1.5-8, FR1.5-10
 */

import ExcelJS from 'exceljs';
import type { MeetingAuditInput } from '@/types/calculator.types';

export interface ParseResult {
  success: true;
  data: MeetingAuditInput;
}

export interface ParseError {
  success: false;
  error: {
    code: string;
    message: string;
    details?: string[];
  };
}

export type ExcelParseResult = ParseResult | ParseError;

/**
 * Expected cell locations in the template
 * These match the template generated by excel-template.ts
 *
 * Template structure:
 * Row 1: Title
 * Row 2: Subtitle
 * Row 3: Attribution
 * Row 5: Instructions header
 * Rows 6-9: Instructions
 * Row 11: "Meeting Details" header
 * Rows 12-14: Meeting inputs
 * Row 16: Salary header
 * Row 17: Salary column headers
 * Rows 18-21: Salary band inputs
 */
const CELL_LOCATIONS = {
  meetingCount: 'B12',
  averageAttendees: 'B13',
  averageDuration: 'B14',
  executive: 'B18',
  senior: 'B19',
  midLevel: 'B20',
  entry: 'B21',
};

/**
 * Validates numeric value is a positive number within range
 */
function validateNumeric(
  value: unknown,
  fieldName: string,
  min: number = 1,
  max: number = 10000
): { valid: boolean; value?: number; error?: string } {
  if (value === null || value === undefined || value === '') {
    return { valid: false, error: `${fieldName} is required` };
  }

  const num = typeof value === 'number' ? value : Number(value);

  if (isNaN(num)) {
    return { valid: false, error: `${fieldName} must be a number` };
  }

  if (num < min) {
    return { valid: false, error: `${fieldName} must be at least ${min}` };
  }

  if (num > max) {
    return { valid: false, error: `${fieldName} must be at most ${max}` };
  }

  return { valid: true, value: num };
}

/**
 * Gets cell value, handling formulas and different value types
 */
function getCellValue(worksheet: ExcelJS.Worksheet, cellRef: string): unknown {
  const cell = worksheet.getCell(cellRef);

  // Handle formula results
  if (cell.formula) {
    return cell.result;
  }

  return cell.value;
}

/**
 * Parses an uploaded Excel file and extracts meeting audit data
 */
export async function parseExcelTemplate(buffer: ArrayBuffer): Promise<ExcelParseResult> {
  try {
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(buffer);

    // Get the first worksheet
    const worksheet = workbook.getWorksheet(1);
    if (!worksheet) {
      return {
        success: false,
        error: {
          code: 'INVALID_FILE',
          message: 'Could not find worksheet in Excel file',
        },
      };
    }

    const errors: string[] = [];

    // Parse meeting details
    const meetingCountResult = validateNumeric(
      getCellValue(worksheet, CELL_LOCATIONS.meetingCount),
      'Number of meetings',
      1,
      1000
    );
    if (!meetingCountResult.valid) errors.push(meetingCountResult.error!);

    const attendeesResult = validateNumeric(
      getCellValue(worksheet, CELL_LOCATIONS.averageAttendees),
      'Average attendees',
      1,
      500
    );
    if (!attendeesResult.valid) errors.push(attendeesResult.error!);

    const durationResult = validateNumeric(
      getCellValue(worksheet, CELL_LOCATIONS.averageDuration),
      'Duration',
      5,
      480
    );
    if (!durationResult.valid) errors.push(durationResult.error!);

    // Parse salary distribution
    const executiveResult = validateNumeric(
      getCellValue(worksheet, CELL_LOCATIONS.executive),
      'Executive count',
      0,
      500
    );
    if (!executiveResult.valid) errors.push(executiveResult.error!);

    const seniorResult = validateNumeric(
      getCellValue(worksheet, CELL_LOCATIONS.senior),
      'Senior count',
      0,
      500
    );
    if (!seniorResult.valid) errors.push(seniorResult.error!);

    const midLevelResult = validateNumeric(
      getCellValue(worksheet, CELL_LOCATIONS.midLevel),
      'Mid-level count',
      0,
      500
    );
    if (!midLevelResult.valid) errors.push(midLevelResult.error!);

    const entryResult = validateNumeric(
      getCellValue(worksheet, CELL_LOCATIONS.entry),
      'Entry count',
      0,
      500
    );
    if (!entryResult.valid) errors.push(entryResult.error!);

    // Return early if validation errors
    if (errors.length > 0) {
      return {
        success: false,
        error: {
          code: 'VALIDATION_ERROR',
          message: 'Invalid data in template',
          details: errors,
        },
      };
    }

    // Validate salary distribution totals
    const totalDistribution =
      (executiveResult.value || 0) +
      (seniorResult.value || 0) +
      (midLevelResult.value || 0) +
      (entryResult.value || 0);

    if (totalDistribution !== attendeesResult.value) {
      return {
        success: false,
        error: {
          code: 'DISTRIBUTION_MISMATCH',
          message: `Salary band total (${totalDistribution}) must equal average attendees (${attendeesResult.value})`,
        },
      };
    }

    // Build the meeting data object
    const meetingData: MeetingAuditInput = {
      meetingCount: meetingCountResult.value!,
      averageAttendees: attendeesResult.value!,
      averageDuration: durationResult.value!,
      salaryDistribution: {
        executive: executiveResult.value || 0,
        senior: seniorResult.value || 0,
        midLevel: midLevelResult.value || 0,
        entry: entryResult.value || 0,
      },
    };

    return {
      success: true,
      data: meetingData,
    };
  } catch (error) {
    console.error('[excel-parser] Error parsing file:', error);
    return {
      success: false,
      error: {
        code: 'PARSE_ERROR',
        message: 'Failed to parse Excel file. Please ensure it is a valid .xlsx file.',
      },
    };
  }
}

/**
 * Validates that the file is a valid Excel file
 */
export function isValidExcelFile(file: File): boolean {
  const validTypes = [
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel',
  ];

  return (
    validTypes.includes(file.type) ||
    file.name.endsWith('.xlsx') ||
    file.name.endsWith('.xls')
  );
}
